name: PowerScrolls
version: '1.0'
main: me.tastycake.itemsCorePowerScrolls.Main
api-version: '1.20'
authors: [ TastyCake ]
description: ItemsCore addon that adds the ability to create power scrolls and add them to items
depend:
  - ItemsCore

commands:
  scrollchamber:
